[deps]
Alpine = "07493b3f-dabb-5b16-a503-4139292d7dd4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Gogeta = "8b0c908c-0e18-4590-8d3d-9c2483fd76bf"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
